version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: "library/"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    rebase-strategy: disabled
